-- C++/C byte-array generator shared by the embed_cxx and payload_extract rules.
--
-- Produces three families of output:
--   * C header   (.h)   — simple unsigned char name[] + name_size
--   * C++ header (.hpp) — namespace-wrapped; either constexpr arrays/spans or
--                         consteval functions returning std::array
--   * C++ module (.cppm) — export module + export namespace wrapper
--
-- Each data member is described by an entry whose content is supplied one of
-- four ways: as an in-memory byte string emitted as hex literals, as a path the
-- preprocessor copies via #embed, as a path the assembler copies verbatim via
-- .incbin (see the 'incbin' group option), or -- for entries with no backing
-- file -- as a literal value given inline.  The hex path buffers the whole
-- payload, so a large blob belongs in incbin or embed_macro instead.

local hex = import("embed_hex")

local BANNER = "// Generated by the embed_cxx rule (xmake). Do not edit."

-- Escapes a filesystem path for use inside a C string literal.
local function c_escape(s)
    return s:gsub([[\]], [[\\]]):gsub([["]], [[\"]])
end

-- Returns output-bound emit helpers:
--   emit(fmt, ...)   formatted line + newline
--   inline(...)      literal line + newline (no formatting)
local function make_emit(output)
    local function emit(fmt, ...)
        output:write(string.format(fmt, ...), "\n")
    end
    local function inline(...)
        output:write(..., "\n")
    end
    return emit, inline
end

-- A C header declares its arrays at column 0, so its payload sits one level in.
local C_BODY_INDENT = "    "

-- Writes one entry's payload at `indent`: the bytes as hex literals, or the
-- #embed directive that stands in for them.  A zero-sized entry writes nothing,
-- leaving the opening brace directly followed by its closing one.
local function write_payload(output, entry, indent)
    if entry.size == 0 then
        return
    end
    if entry.embed_path then
        -- #embed is a preprocessing directive: it must start a line.  Leading
        -- whitespace is legal there and lines the directive up with the hex it
        -- replaces.  It expands to the file's bytes, one array element each.
        output:write(indent, '#embed "', c_escape(entry.embed_path), '"\n')
    else
        output:write(hex.hex_body(entry.data, indent), "\n")
    end
end

-- Emits one C++ data member.  entry = {name, size, data|embed_path|incbin_path}.
-- `member` is the leading whitespace of the member itself, so a group without a
-- namespace indents from column 0 instead of inheriting the namespace's level.
local function write_cpp_member(output, entry, consteval, member)
    local emit = make_emit(output)
    member = member or ""

    if entry.incbin_path then
        -- The bytes already live in the assembler's object; all that remains is
        -- a constant span over them.  The size is written here as a literal
        -- rather than derived from a _end symbol, because a pointer difference
        -- between two unrelated objects is not a constant expression, and
        -- keeping the span constexpr is what lets consumers use it in static
        -- initialisers (the same role std::array played).
        emit("%sconstexpr std::span<const unsigned char> %s = { %s, %d };", member, entry.name, entry.symbol, entry.size)
        return
    end

    if consteval then
        -- A function, not an object: the caller decides what to do with the
        -- array (bind it, store it elsewhere, run an algorithm over it) and
        -- nothing reaches storage unless it is actually used.
        local inner = member .. "    "
        emit("%sconsteval auto %s() {\n%sconstexpr std::array<unsigned char, %d> raw = {"
            , member
            , entry.name
            , inner
            , entry.size
        )
        write_payload(output, entry, inner .. "    ")
        emit("%s};\n%sreturn raw;\n%s}\n%sconsteval std::size_t %s_size() { return %d; }"
            , inner
            , inner
            , member
            , member
            , entry.name
            , entry.size
        )
    else
        emit("%sconstexpr std::array<unsigned char, %d> %s = {", member, entry.size, entry.name)
        write_payload(output, entry, member .. "    ")
        emit("%s};", member)
    end
end

-- Emits one C header member.  See write_cpp_member for the entry shape.
local function write_c_entry(output, entry)
    local emit = make_emit(output)

    if entry.incbin_path then
        -- The storage lives in the assembler's object, so the header can only
        -- declare it.  An enum carries the length as a compile-time constant
        -- without giving it storage or a second exported symbol.  The symbol
        -- name is the one the generated .S defines, so it must match exactly.
        emit("extern const unsigned char %s[];\nenum { %s_size = %d };", entry.symbol, entry.name, entry.size)
        return
    end

    -- 'const' so the payload lands in .rodata instead of .data: a blob of a few tens of KB per
    -- entry would otherwise be copied into writable memory for the life of the process.  In C++
    -- this also gives the array internal linkage, so a header included from more than one
    -- translation unit cannot produce duplicate symbols.
    emit("const unsigned char %s[] = {", entry.name)
    write_payload(output, entry, C_BODY_INDENT)
    emit("};\n\nunsigned long long %s_size = %d;", entry.name, entry.size)
end

-- Emits a full C header (.h) wrapping one or more entries.  The result is plain
-- C: no namespace, no <array>/<span>, no C++ keyword.  Members are the classic
-- `unsigned char name[] = {...}` plus a trailing `name_size`, or, under incbin,
-- an extern declaration plus a size enum because the bytes live elsewhere.
local function write_c_header(output, entries)
    local emit, inline = make_emit(output)

    inline(BANNER)
    emit("#pragma once")
    -- No diagnostic pragma here: #embed is standard C23, so neither clang nor
    -- GCC warns about it in C, and "-Wc++23-extensions" is C++-only, so
    -- naming it would make every -Werror C build fail on the generated header.
    for _, entry in ipairs(entries) do
        inline("")
        write_c_entry(output, entry)
    end
end

-- Writes the shared C++ scaffolding (pragma/imports + namespace open/close)
-- around a body emit callback.  `entries` is the group's full entry list; only
-- the incbin ones are needed here, to hoist their extern declarations above
-- "export module".
local function write_cpp_wrapper(output, opts, entries, body)
    local emit, inline = make_emit(output)
    inline(BANNER)

    -- Both branches leave the cursor on a fresh, blank line, so every section
    -- below can simply start writing and the spacing stays the same whether a
    -- namespace, an incbin block or an exported module comes next.
    if opts.mode == "module" then
        emit(""
            .. "module;\n"
            .. "\n"
            .. "#include <array>\n"
        )
    else
        emit(""
            .. "#pragma once\n"
            .. "\n"
            .. "#include <array>\n"
        )
    end

    -- incbin members are spans over symbols the assembler defines, so they need
    -- <span> as well.  Their declarations belong in the global module fragment,
    -- ahead of "export module": a declaration with C language linkage is not
    -- module-owned, but only outside the module purview is that guaranteed, and
    -- there it plainly resolves against the assembler's object at link time.
    local incbin = {}
    for _, entry in ipairs(entries) do
        if entry.incbin_path then
            incbin[#incbin + 1] = entry
        end
    end
    if #incbin > 0 then
        -- No leading blank: the include above already left one behind.
        inline("#include <span>")
        inline("")
        inline("extern \"C\" {")
        for _, entry in ipairs(incbin) do
            inline(string.format("extern const unsigned char %s[];", entry.symbol))
        end
        inline("}")
        inline("")
    end

    if opts.mode == "module" then
        -- The cursor is already on a blank line courtesy of the include above.
        emit("export module %s;\n", opts.module)
    end

    -- #embed reached C23 but is still a Clang extension in C++, so only
    -- clang needs silencing here.  GCC does not warn in C++ at all, and its
    -- "-Wc++23-extensions" spelling is rejected outright in C mode, which
    -- would break any consumer building with -Werror.
    if opts.embed_macro then
        inline("#if defined(__clang__)")
        inline("#pragma clang diagnostic ignored \"-Wc23-extensions\"")
        inline("#endif")
        inline("")
    end

    if opts.namespace then
        if opts.mode == "module" then
            emit("export namespace %s\n{", opts.namespace)
        else
            emit("namespace %s\n{", opts.namespace)
        end
    end

    body()

    if opts.namespace then
        if opts.mode == "module" then
            inline("}")
        else
            inline("} // namespace " .. opts.namespace)
        end
    end
end

-- Entry backed by an in-memory byte string.
local function entry_from_data(name, data)
    return {name = name, data = data, size = data and #data or 0}
end

-- Entry backed by an absolute source path emitted via #embed.
local function entry_from_embed(name, source, size)
    return {name = name, embed_path = path.absolute(source), size = size}
end

-- Entry backed by an absolute source path copied verbatim by the assembler's
-- .incbin.  The bytes never pass through Lua or the C++ front-end: they go
-- from the file straight into the object's .rodata.  Only the digest travels
-- through the generated sources, so a payload edit still invalidates the build.
local function entry_from_incbin(name, source, size, digest)
    return {name = name, incbin_path = path.absolute(source), size = size, digest = digest}
end

-- Generates a multi-entry file.  entries is a list of entry tables built by the
-- entry_from_* helpers above.  mode "c-header" emits a C header, anything else a
-- C++ header or module.
function write_embedded(output_path, opts, entries)
    opts = opts or {}

    local output = io.open(output_path, "w")
    if not output then
        os.raise("embed_cxx: unable to open output file: %s", output_path)
    end

    if opts.mode == "c-header" then
        write_c_header(output, entries)
    else
        local member = opts.namespace and "    " or ""
        write_cpp_wrapper(output, opts, entries, function()
            for _, entry in ipairs(entries) do
                write_cpp_member(output, entry, opts.consteval, member)
            end
        end)
    end

    output:write("\n")
    output:close()
end

-- Generates a single-entry file, wrapping a raw byte string (nil for an empty
-- placeholder).  This is the entry point payload_extract uses; `lang = "c"`
-- selects the C header, otherwise `mode` picks a C++ header or module.
-- Returns the generated file path.
function write_file(outdir, basename, opts, data)
    opts = opts or {}
    local lang = opts.lang or "cxx"
    local mode = opts.mode or "header"

    os.mkdir(outdir)
    local ext = lang == "c" and ".h" or (mode == "module" and ".cppm" or ".hpp")

    -- The emitters key off `mode`, so fold the legacy `lang` switch into it and
    -- let write_embedded do the actual generation.  A module unit still needs a
    -- name, and callers that predate the `module` option (payload_extract) do not
    -- pass one -- formatting a nil here would emit "export module nil;", so apply
    -- the same default resolve_options uses for groups.
    local module_name = opts.module
    if mode == "module" and not module_name then
        module_name = "embed." .. basename
    end

    write_embedded(path.join(outdir, basename .. ext), {
        mode = lang == "c" and "c-header" or mode,
        module = module_name,
        namespace = opts.namespace,
        consteval = opts.consteval,
        embed_macro = opts.embed_macro,
    }, { entry_from_data(basename, data) })

    return path.join(outdir, basename .. ext)
end

-- Bump whenever the generated text changes.  The content hash in generate_group
-- only tracks the payload digests, so without this a rule update would keep
-- serving stale artifacts (e.g. a .S whose assembler syntax no longer assembles).
local GENERATOR_VERSION = 2

-- Writes the assembler companion for an incbin group.  One .incbin per entry,
-- each preceded by its payload digest: the file stays a few lines, but because
-- the digest is part of its text a payload edit rewrites this file, so the build
-- system recompiles it and relinks with the new bytes.  Without that the .S
-- would look unchanged and the binary would silently keep stale data.
local function write_incbin_asm(output_path, entries)
    local output = io.open(output_path, "w")
    if not output then
        os.raise("embed_cxx: unable to open output file: %s", output_path)
    end

    -- '#' is the only line comment both GNU as and LLVM MC accept on x86;
    -- '--' is rejected as an unexpected token, so it cannot be used here.
    output:write("# Generated by the embed_cxx rule (xmake). Do not edit.\n")
    output:write("# source=\"incbin\": the payload is copied verbatim into .rodata,\n")
    output:write("# so nothing here has to be parsed or hex-escaped.\n")
    output:write("\t.section\t.rodata\n")

    for _, entry in ipairs(entries) do
        if entry.incbin_path then
            output:write("\n")
            output:write(string.format("# %s  sha256:%s\n", entry.name, entry.digest or "?"))
            output:write(string.format("\t.balign\t8\n"))
            output:write(string.format("\t.globl\t%s\n", entry.symbol))
            output:write(string.format("\t.type\t%s, @object\n", entry.symbol))
            output:write(string.format("%s:\n", entry.symbol))
            output:write(string.format("\t.incbin\t\"%s\"\n", c_escape(entry.incbin_path)))
        end
    end

    output:close()
end

-- Resolves a configured entry into a source entry.  `representation` selects how
-- the bytes reach the artifact: "hex" (the default) loads them into memory and
-- emits them as ,-separated literals; "embed" hands the absolute source path to a
-- #embed directive; "incbin" hands it to the assembler and passes only the digest
-- along.  `symbol_prefix` keeps generated linker symbols unique across groups,
-- since two groups may well name different files the same thing.
local function resolve_entry(entry, representation, digest, symbol_prefix)
    local name = entry[1]
    local src = entry[2]
    if type(src) == "table" then
        -- In-memory value with no backing file, so #embed and .incbin have
        -- nothing to point at.
        return entry_from_data(name, src)
    end

    local size = os.filesize(src) or 0
    if representation == "embed" then
        return entry_from_embed(name, src, size)
    end
    if representation == "incbin" then
        local resolved = entry_from_incbin(name, src, size, digest)
        -- Only a non-empty payload gets a symbol: there are no bytes for an
        -- empty .incbin to define, and the emitters already treat a zero-sized
        -- entry as "nothing to emit".
        if size > 0 then
            resolved.symbol = symbol_prefix .. name
        end
        return resolved
    end
    if size <= 0 then
        return entry_from_data(name, "")
    end

    local handle = io.open(src, "rb")
    if not handle then
        os.raise("embed_cxx: input not found: %s", src)
    end
    -- NB: read("<n>") on this xmake runtime caps out around ~1 MiB and would
    -- silently truncate large blobs; read("*a") reads the whole file.  We load
    -- the bytes into memory and emit them with hex_body.
    local data = handle:read("*a")
    handle:close()
    if not data then
        os.raise("embed_cxx: unable to read input: %s", src)
    end
    return entry_from_data(name, data)
end

local PREFIX = "embed."

-- Collects configured groups from the target values under PREFIX.
local function collect_groups(target)
    local groups = {}
    local all = target:get("values")
    if type(all) ~= "table" then
        return groups
    end
    for key, val in pairs(all) do
        if type(key) == "string" and key:sub(1, #PREFIX) == PREFIX and type(val) == "table" then
            local rest = key:sub(#PREFIX + 1)
            local dot = rest:find(".", 1, true)
            local id = dot and rest:sub(1, dot - 1) or rest
            local group = groups[id] or {}
            if dot then
                group[rest:sub(dot + 1)] = val
            else
                for item_key, item_val in pairs(val) do
                    group[item_key] = item_val
                end
            end
            groups[id] = group
        end
    end
    return groups
end

local MODES = { module = true, header = true, ["c-header"] = true }

-- The set of accepted mode strings, in the order used by the error message.
local MODE_LIST = "'module', 'header' or 'c-header'"

-- Turns a group's raw dictionary into a validated option set, raising on any
-- combination that cannot work or that would be silently ignored.  Validation
-- lives here (once) rather than being spread over the emitters so a group is
-- rejected up front instead of producing a subtly wrong artifact.
--
-- Resolved keys:
--   mode          "module"|"header"|"c-header"; default "header"
--   module        module unit name; defaults to "embed."<id> in module mode,
--                 forbidden in the other two
--   namespace     optional C++ namespace; meaningless (and rejected) for C
--   consteval     emit consteval accessors instead of inline constexpr members
--   incbin        let the assembler copy payloads verbatim into .rodata
--   embed_macro   emit a #embed directive per entry instead of hex literals
local function resolve_options(id, raw)
    local mode = raw.mode or "header"
    if not MODES[mode] then
        os.raise("embed_cxx: group '%s' has an unknown mode '%s'; expected %s", id, mode, MODE_LIST)
    end

    local consteval = raw.consteval == true
    local incbin = raw.incbin == true
    local embed_macro = raw.embed_macro == true
    local module_name = raw.module
    local namespace = raw.namespace

    if incbin and embed_macro then
        os.raise("embed_cxx: group '%s' cannot set both 'incbin' and 'embed_macro'; pick one", id)
    end
    if incbin and consteval then
        -- A span over an assembler symbol is already a literal type, so a
        -- consteval accessor would only add an indirection; reject rather than
        -- ignore so the flag never silently does nothing.
        os.raise("embed_cxx: group '%s' cannot combine 'incbin' with 'consteval'; a span is already constexpr", id)
    end
    if module_name ~= nil and mode ~= "module" then
        os.raise("embed_cxx: group '%s' sets 'module' but its mode is '%s'; 'module' is only valid in 'module' mode", id, mode)
    end
    if mode == "module" and not module_name then
        module_name = "embed." .. id
    end

    if mode == "c-header" then
        if namespace ~= nil then
            os.raise("embed_cxx: group '%s' cannot use 'namespace' in c-header mode; C has no namespaces", id)
        end
        if consteval then
            os.raise("embed_cxx: group '%s' cannot use 'consteval' in c-header mode; it is C++-only", id)
        end
    end

    if embed_macro and mode == "module" then
        -- #embed inside a .cppm directly ICEs clang < 23 even though it works in
        -- a header #include'd from the global module fragment; reject it.
        os.raise("embed_cxx: group '%s' cannot use 'embed_macro' in module mode (ICE in clang modules)", id)
    end

    return {
        mode = mode,
        module = module_name,
        namespace = namespace,
        consteval = consteval,
        incbin = incbin,
        embed_macro = embed_macro,
    }
end

-- The single active payload representation for a resolved group, used as the
-- key for the internal code paths and the generated output directory.
local function representation(opts)
    if opts.incbin then
        return "incbin"
    end
    if opts.embed_macro then
        return "embed"
    end
    return "hex"
end

-- Generates the artifact for one configured group.
-- Returns the resolved option set, or nil if the group was skipped.
local function generate_group(target, id, raw)
    local config = import("core.project.config")
    local opts = resolve_options(id, raw)
    local source = representation(opts)
    local mode = opts.mode
    local consteval = opts.consteval
    local module_name = opts.module
    local namespace = opts.namespace
    local entries = raw.entries or {}

    local output_name
    if mode == "module" then
        output_name = raw.output or (module_name .. ".cppm")
    elseif mode == "c-header" then
        output_name = raw.output or ("embedded_" .. id .. ".h")
    else
        output_name = raw.output or ("embedded_" .. id .. ".hpp")
    end

    -- Derive a shared output directory from the group's identity so equal
    -- groups across targets reuse one artifact.  Mode, consteval and the
    -- payload representation are part of the key, keeping distinct outputs in
    -- separate folders.
    local output_dir
    if raw.outdir then
        output_dir = path.absolute(raw.outdir)
    else
        local group_key = id .. "|" .. mode .. "|" .. tostring(consteval) .. "|" .. source .. "|" .. tostring(namespace)
        for _, item in ipairs(entries) do
            local name = item[1]
            local src = item[2]
            local source_key = type(src) == "table" and "" or path.absolute(src)
            group_key = group_key .. "|" .. name .. "=" .. source_key
        end
        local key_file = path.join(path.absolute(config.builddir()), ".gens", "embed", ".groupkey.tmp")
        -- The scratch file is written before anything else in this function, so on a fresh
        -- tree (no build dir at all) its parent has to exist first.
        os.mkdir(path.directory(key_file))
        io.writefile(key_file, group_key)
        local group_hash = hash.sha256(key_file) or "shared"
        os.rm(key_file)
        output_dir = path.join(path.absolute(config.builddir()), ".gens", "embed", group_hash)
    end

    local output = path.join(output_dir, output_name)
    if not os.isdir(output_dir) then
        os.mkdir(output_dir)
    end

    -- incbin groups also emit an assembler companion next to the header/module.
    local asm_output
    if source == "incbin" then
        asm_output = path.join(output_dir, raw.asm or ("embed_" .. id .. ".S"))
    end

    -- Content-hash the sources so unchanged rebuilds don't regenerate the
    -- multi-MB header on every configure.  The digests are kept per entry so
    -- the .incbin file can carry them, which is what makes a payload edit
    -- invalidate the compiled object instead of silently going stale.
    local hash_file = output .. ".hash"
    local current_hash
    local missing = {}
    local digests = {}
    do
        local parts = { "genv:" .. GENERATOR_VERSION }
        for index, item in ipairs(entries) do
            local source = item[2]
            if type(source) == "string" then
                local source_path = path.absolute(source)
                if os.isfile(source_path) then
                    local digest = hash.sha256(source_path) or ""
                    digests[index] = digest
                    parts[#parts + 1] = digest
                else
                    parts[#parts + 1] = "missing:" .. source_path
                    missing[#missing + 1] = source_path
                end
            end
        end
        current_hash = table.concat(parts, ":")
    end

    local symbol_prefix = "embed_" .. id .. "_"

    if #missing > 0 then
        -- Sources can be produced later by another target (gen-glyph-gids shapes the
        -- emoji -> gid table at build time), so a configure-time run must not fail
        -- because they don't exist yet.  It must not simply skip the group either:
        -- a group in "module" mode has to be registered in the target's module graph
        -- during this configure, and xmake resolves `import <module>` against the
        -- files that exist right now, so an unregistered module aborts the configure
        -- with "missing <module> dependency for module ...".
        --
        -- So write a placeholder carrying the same declarations with zero-length
        -- members, register it, and leave the hash file absent so the build-time pass
        -- regenerates the real content right before the target's files are compiled
        -- (mopick's before_build calls generate() again).  Nothing ever links the
        -- placeholder: the generator reruns in the same build.
        local placeholder = {}
        for index, item in ipairs(entries) do
            placeholder[index] = entry_from_data(item[1], "")
        end
        local tmp = output .. ".placeholder.tmp"
        write_embedded(tmp, opts, placeholder)
        os.tryrm(output)
        os.mv(tmp, output)
        if asm_output then
            -- No payload to incbin yet: emit the section but no symbols, so the
            -- placeholder stays assemblable.
            local asm_tmp = asm_output .. ".placeholder.tmp"
            write_incbin_asm(asm_tmp, {})
            os.tryrm(asm_output)
            os.mv(asm_tmp, asm_output)
        end
        os.tryrm(hash_file)
        vprint("[embed_cxx] placeholder %s: missing %s", output_name, table.concat(missing, ", "))
    end

    local output_mtime = os.isfile(output) and os.mtime(output)
    local old_hash = os.isfile(hash_file) and io.readfile(hash_file)
    if (#missing == 0) and ((not output_mtime) or (current_hash ~= old_hash)) then
        local resolved = {}
        for index, item in ipairs(entries) do
            resolved[#resolved + 1] = resolve_entry(item, source, digests[index], symbol_prefix)
        end
        local tmp = output .. ".tmp"
        write_embedded(tmp, opts, resolved)
        os.tryrm(output)
        os.mv(tmp, output)
        if asm_output then
            local asm_tmp = asm_output .. ".tmp"
            write_incbin_asm(asm_tmp, resolved)
            os.tryrm(asm_output)
            os.mv(asm_tmp, asm_output)
        end
        io.writefile(hash_file, current_hash)
        vprint("[embed_cxx] generated %s", path.relative(output, os.projectdir()))
    end

    target:add("includedirs", output_dir, {force = true})
    if asm_output then
        -- .incbin needs an assembler, and xmake's cxx rule already compiles .S files with the
        -- toolchain assembler: adding the file is enough. Note that this must NOT be expressed
        -- as target:add("languages", "asm") -- xmake validates `languages` against the
        -- languages it knows (c, cxx, objc, ...), warns "unknown language value 'asm'" and then
        -- drops the target's build tasks, so nothing gets compiled or linked.
        -- Registering the .S puts its object in the target, so the linker
        -- resolves the extern "C" symbols the generated C++ declares.
        target:add("files", asm_output)
        vprint("[embed_cxx] generated %s", path.relative(asm_output, os.projectdir()))
    end
    if mode == "module" then
        target:add("files", output)
    end
    return opts
end

-- Entry point for the embed_cxx rule: generates every configured group.
function generate(target)
    local groups = collect_groups(target)
    local ids = {}
    for id in pairs(groups) do
        ids[#ids + 1] = id
    end
    table.sort(ids)
    local uses_embed = false
    for _, id in ipairs(ids) do
        local opts = generate_group(target, id, groups[id])
        if opts and opts.embed_macro then
            uses_embed = true
        end
    end
    if uses_embed then
        -- xmake's build cache re-preprocesses every source to build its
        -- caching hash, and #embed expansion makes that preprocess pass cost
        -- as much as a full compile (~GBs of tokens).  Targets that embed via
        -- #embed keep nothing to cache, so skip the cache entirely.
        local ok = false
        if type(target.set_policy) == "function" then
            target:set_policy("build.ccache", false)
            ok = true
        else
            -- Some xmake builds expose set_policy only inside the target scope
            -- (not as an instance method); write it into the scope info instead.
            local info = target:info()
            if type(info) == "table" then
                info.policy = info.policy or {}
                info.policy["build.ccache"] = false
                target._POLICIES = nil
                ok = true
            end
        end
        if not ok then
            vprint("embed_cxx: warnings: could not disable the build cache; #embed preprocessing may be slow")
        end
    end
end

