
-- Tasks -------------------------------------------------------------------------------------------
task("pinfo")
    set_menu({
        usage       = "xmake pinfo [target]",
        description = "Shows the target info box(es) from the cached configuration generated by `xmake f`, without reconfiguring. Prints every target when no name is given.",
        options     = {
            {nil, "target", "v", nil,  "The target name to show info for. Prints all targets when unset."}
        }
    })
    on_run(function ()
        import("core.project.project")
        import("core.project.config" )
        import("core.base.option" )
        import("cfg.triple"  )
        import("lang.perl"   )

        config.load()

        local name = option.get("target")
        for _, t in ipairs(project.ordertargets()) do
            if name == nil or t:name() == name then
                if t:rule("perl") then
                    perl.print_info(t)
                else
                    local info = triple.get(t)
                    if info then
                        triple.print_info(t, info)
                    end
                end
            end
        end
    end)
task_end()

task("setup-perl")
    set_menu({
        usage       = "xmake setup-perl",
        description = "Validates the perl/carton environment and installs the dependencies of every root_dir declared by targets using add_rules(\"perl\")."
    })
    on_run(function ()
        import("lang.perl")
        perl.setup_cli()
    end)
task_end()

